name: naver-crawler

on:
  schedule:
    - cron: '0 23 * * *'  # KST 오전 8시 = UTC 전날 23시
  workflow_dispatch:

jobs:
  run-crawler:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4 pandas

    - name: Run crawler
      run: python naver.py
      env:
        GMAIL_SENDER: ${{ secrets.GMAIL_SENDER }}
        GMAIL_RECEIVER: ${{ secrets.GMAIL_RECEIVER }}
        GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
